version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs-app
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - database
  #     - redis
  #   env_file:
  #     - .env
  #   environment:
  #     - TYPEORM_CONNECTION=postgres
  #     - TYPEORM_HOST=database
  #     - TYPEORM_PORT=5432
  #     - TYPEORM_USERNAME=postgres
  #     - TYPEORM_PASSWORD=postgres
  #     - TYPEORM_DATABASE=postgres
  #     - TYPEORM_ENTITIES=dist/**/*.entity{.ts,.js}
  #     - TYPEORM_SYNCHRONIZE=false
  #     - TYPEORM_LOGGING=false
  #   command: yarn start

  database:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
